
services:
  server:
    build:
      context: .
    container_name: propelize_server
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: propelize_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "${DB_PORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
